name: cladder12
channels:
  - nvidia/label/cuda-12.1.1
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch==2.1.2
  - torchvision==0.16.2
  - torchaudio==2.1.2
  - pytorch-cuda=12.1
  - cuda-nvcc=12.1
  - cuda-toolkit
  - scikit-learn
  - jupyterlab
  - tqdm
  - matplotlib
  - jsonnet
  - cmake
  - pomegranate==0.14.8
  - dowhy
  - pip
  - pip:
      - munch
      - ruamel.yaml
      - typed-argument-parser
      - pynvml
      - psutil
      - jsonargparse[all]
      - docopt
      - wandb
      - python-dotenv
      - cilog
      - einops
      - openai
      - omnibelt==0.7.6
      - omnifig==1.0.1
      - omniply==0.1.1
      - pytest
      - plotly
      - pandas
      - scipy
      - peft
      - tabulate
      - efficiency
      - transformers
      - trl
      - hydra-core