just_scoring: False
enable_cot: False
enable_fewshot: False
majority_vote: False
ask_about: answer
given_cot_until_step: null
model_versions:
    - gpt-4o-mini
#    - gpt-3.5-turbo
#    - gpt-4o
# COT + ask query type not supported